/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DHTNode_SupernodeInterface_CONSTANTS_H
#define DHTNode_SupernodeInterface_CONSTANTS_H

#include "DHTNode_SupernodeInterface_types.h"



class DHTNode_SupernodeInterfaceConstants {
 public:
  DHTNode_SupernodeInterfaceConstants();

};

extern const DHTNode_SupernodeInterfaceConstants g_DHTNode_SupernodeInterface_constants;



#endif
