/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FileServerInterface_CONSTANTS_H
#define FileServerInterface_CONSTANTS_H

#include "FileServerInterface_types.h"



class FileServerInterfaceConstants {
 public:
  FileServerInterfaceConstants();

};

extern const FileServerInterfaceConstants g_FileServerInterface_constants;



#endif
