// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FileServerInterface.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class FileServerInterfaceHandler : virtual public FileServerInterfaceIf {
 public:
  FileServerInterfaceHandler() {
    // Your initialization goes here
  }

  void Write(const WriteFile& fileInfo, const int64_t flags) {
    // Your implementation goes here
    printf("Write\n");
  }

  void Read(ReadFile& _return, const std::string& filename, const int64_t flags) {
    // Your implementation goes here
    printf("Read\n");
  }

  void getAllServers(std::vector<ServerInfo> & _return) {
    // Your implementation goes here
    printf("getAllServers\n");
  }

  int64_t Register(const ServerInfo& myInfo) {
    // Your implementation goes here
    printf("Register\n");
  }

  int64_t getVersion(const std::string& filename) {
    // Your implementation goes here
    printf("getVersion\n");
  }

  void updateFile(WriteFile& _return, const WriteFile& appendFile, const int64_t version, const int64_t append_flag) {
    // Your implementation goes here
    printf("updateFile\n");
  }

  void getFile(ReadFile& _return, const std::string& filename) {
    // Your implementation goes here
    printf("getFile\n");
  }

  void listFiles(std::vector<FileInfo> & _return) {
    // Your implementation goes here
    printf("listFiles\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<FileServerInterfaceHandler> handler(new FileServerInterfaceHandler());
  shared_ptr<TProcessor> processor(new FileServerInterfaceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

