/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MR_ComputeNodeInterface_constants.h"



const MR_ComputeNodeInterfaceConstants g_MR_ComputeNodeInterface_constants;

MR_ComputeNodeInterfaceConstants::MR_ComputeNodeInterfaceConstants() {
}



