/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MR_ServerInterface_constants.h"



const MR_ServerInterfaceConstants g_MR_ServerInterface_constants;

MR_ServerInterfaceConstants::MR_ServerInterfaceConstants() {
}



