/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MR_ServerInterface_CONSTANTS_H
#define MR_ServerInterface_CONSTANTS_H

#include "MR_ServerInterface_types.h"



class MR_ServerInterfaceConstants {
 public:
  MR_ServerInterfaceConstants();

};

extern const MR_ServerInterfaceConstants g_MR_ServerInterface_constants;



#endif
