#makefile
# CSci 4061 Spring 2015 Assignment 3
# Henry Grittner, 4560922
# David Schoder, 4552990
# This is the makefile for the file system test program

test: test.c mini_filesystem.c mini_filesystem.h miscfuncs.h testfuncs.h
	gcc -o test test.c mini_filesystem.c
