#makefile
# CSci 4061 Spring 2015 Assignment 4
# Henry Grittner, 4560922
# David Schoder, 4552990
# This is the makefile for the image manager program

image_manager: image_manager.c miscfuncs.h threadfuncs.h
	gcc -pthread -o image_manager image_manager.c
