#makefile
# CSci 4061 Spring 2015 Assignment 2
# Henry Grittner, 4560922
# David Schoder, 4552990
# This is the makefile for the parallel_convert program

parallel_convert: parallel_convert.c convertfunctions.h funcs.h listfuncs.h
	gcc -o parallel_convert parallel_convert.c
